resources:
  - name: seasocks_github
    type: GitRepo
    configuration:
      path: danimtb/conan-seasocks
      gitProvider: danimtb_github

pipelines:
  - name: seasocks
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: danimtb/pipelines-conanio-gcc8-armv7hf
            tag: latest
    steps:
      - name: configure_environment
        type: Bash
        configuration:
          inputResources:
            - name: seasocks_github
          integrations:
            - name: artifactory
        execution:
          onExecute:
            - conan user
            - conan remote remove conan-center
            - conan remote add artifactory https://art-yalla.jfrog-lab.com/artifactory/api/conan/conan-repo
            - conan user $int_artifactory_user --remote artifactory --password $int_artifactory_apikey
            - conan profile new default --detect
            - conan profile update settings.compiler.libcxx=libstdc++11 default
            - conan profile update settings.arch=armv7hf default
            - add_run_files ~/.conan conan_user_home
      - name: create_app
        type: Bash
        configuration:
          inputResources:
            - name: seasocks_github
              trigger: false
          inputSteps:
            - name: configure_environment
        execution:
          onExecute:
            - restore_run_files conan_user_home ~/.conan
            - conan create $res_seasocks_github_resourcePath --build missing
            - add_run_files ~/.conan conan_user_home2
      - name: upload_app
        type: Bash
        configuration:
          inputSteps:
            - name: create_app
        execution:
          onExecute:
            - restore_run_files conan_user_home2 ~/.conan
            - conan upload --all --confirm "*"
